fin = open ("teleport.in", "r")
fout = open ("teleport.out", "w")
a,b,x,y = map(int, fin.readline().split())
d1 = abs(a-b)
d2 = abs(a-x)+abs(y-b)
d3 = abs(a-y) + abs(b-x)
result = min(d1,min(d2,d3))
fout.write(str(result) + "\n")
fout.close()
